files:
  include: '**/*.scss'
options:
  formatter: beautify
rules:
  indentation:
    - 2
    - size: 4
  no-ids: 0
  no-important: 0
  no-color-literals: 0
  class-name-format:
    - 2
    - convention: snakecase
    - allow-leading-underscore: 1
  no-color-keywords: 0
  hex-length:
    - 2
    - style: long